### ISSUE TITLE
@graphql-tools produces warnings during a webpack build

### ISSUE THREAD

**Issue by marxian** [lola-tech/graphql-kimera#65]
## Detailed Description
When using Kimera to produce a mocked executableSchema for use in a UI with `apollo-link-schema` I've observed warnings from webpack (in this case via create-react-app's `react-scripts`):

```
./node_modules/@graphql-toolkit/file-loading/index.esm.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/@graphql-toolkit/file-loading/index.esm.js
Critical dependency: the request of a dependency is an expression

./node_modules/@graphql-toolkit/file-loading/index.esm.js
Critical dependency: the request of a dependency is an expression

./node_modules/@graphql-toolkit/common/index.esm.js
Critical dependency: the request of a dependency is an expression

./node_modules/@graphql-toolkit/common/index.esm.js
Critical dependency: the request of a dependency is an expression

./node_modules/@graphql-toolkit/common/index.esm.js
Critical dependency: the request of a dependency is an expression

./node_modules/@graphql-toolkit/common/index.esm.js
Critical dependency: the request of a dependency is an expression
```

This problem is exacerbated in CI environments (like travis-ci.org) where the presence of the environment variable `CI=true` causes the build to fail.

## Expected Behaviour
A build should succeed without warnings
## Current Behaviour
```
yarn build:testable
yarn run v1.15.2
$ REACT_APP_MOCKS=true yarn build
$ react-app-rewired build
Creating an optimized production build...

Treating warnings as errors because process.env.CI = true.
Most CI servers set it automatically.

Failed to compile.

./node_modules/@graphql-toolkit/file-loading/index.esm.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/@graphql-toolkit/file-loading/index.esm.js
Critical dependency: the request of a dependency is an expression

./node_modules/@graphql-toolkit/file-loading/index.esm.js
Critical dependency: the request of a dependency is an expression

./node_modules/@graphql-toolkit/common/index.esm.js
Critical dependency: the request of a dependency is an expression

./node_modules/@graphql-toolkit/common/index.esm.js
Critical dependency: the request of a dependency is an expression

./node_modules/@graphql-toolkit/common/index.esm.js
Critical dependency: the request of a dependency is an expression

./node_modules/@graphql-toolkit/common/index.esm.js
Critical dependency: the request of a dependency is an expression


error Command failed with exit code 1.
```

## Steps to Reproduce
You can see this issue in the wild in this PR: https://github.com/neontribe/gbptm/pull/718

Logs from travis should be accessible here: https://travis-ci.org/github/neontribe/gbptm/builds/691708579

## Context (Environment)
Kimera + apollo-link-schema + create-react-app

**Comment by mavv** [comment]
I managed to reproduce it and I will look into this issue asap.

**Comment by marxian** [comment]
Thanks! I'll be trying from my end too.

**Comment by mavv** [comment]
Having done a bit of investigation about the possible causes for this bug, I noticed that the error was actually thrown from one of our dependencies, called `easygraphql-parser`. 

`easygraphql-parser` is using at the moment as its dependency `merge-graphql-schemas` that uses an older and deprecated version of `@graphql-tools` which causes the warning to be thrown.

After doing some testing locally I noticed that solving `easygraphql-parser` https://github.com/EasyGraphQL/easygraphql-parser/issues/33 can fix our issue so I also created a [PR](https://github.com/EasyGraphQL/easygraphql-parser/pull/34) on their repo

**Comment by mavv** [comment]
I installed the new release v1.0.1 on [neontribe/gbptm](https://github.com/neontribe/gbptm) and the warnings are no longer thrown.

@marxian do you think is safe for now to close this issue?

**Comment by marxian** [comment]
Yes, I believe so! Thank you!
