### ISSUE TITLE
Coveralls integration doesn't work

### ISSUE THREAD

**Issue by c10b10** [lola-tech/graphql-kimera#69]
## Detailed Description

A Coveralls report seem to not be working, since they always are reporting 0%. I suggest either fixing or removing them.

## Expected Behaviour

The actual coverage percentage should be reported instead of 0%.

## Current Behaviour

A Coveralls report with 0% appears on each PR. 

## Steps to Reproduce

You can check the report on any PR.

**Comment by mavv** [comment]
The coveralls workflow is flawed and we will fix it very soon

**Comment by mavv** [comment]
I'm sorry for not dealing with this issue earlier. We decided to throw coveralls away and use codecov instead -- see workflow [here](https://github.com/lola-tech/graphql-kimera/blob/master/.github/workflows/nodejs.yml#L31). 

I will close the issue soon after we do some checks
