### ISSUE TITLE
Multiple versions of GraphQL?

### ISSUE THREAD

**Issue by marxian** [lola-tech/graphql-kimera#77]
## Detailed Description
When adding Kimera to an Apollo Server project the server raises an error because of multiple versions of the `graphql` dependency being present.
## Expected Behavior
It'd be nice if this didn't happen , it is a bit of a roadblock for new users.
## Current Behavior
The server crashes when trying to serve mocks
## Workaround
I've worked around this in a yarn-based project by using the `resolutions` field in `package.json`, I don't know what I'd have done if I'd been in npm.

**Comment by c10b10** [comment]
This should help: https://indepth.dev/npm-peer-dependencies/
